### ISSUE TITLE
Please answer "why?" early in the docs.

### ISSUE THREAD

**Issue by guettli** [OPMDG/opm-doc#15]
I looked at this: https://opm.readthedocs.io/

Unfortunately like most software docs, your docs start with details.

Please answer the question "why?" early in the docs.

Why is OPM great? Benefits, why better then powa, PGObserver, ....?

**Comment by rjuju** [comment]
Hi,

This software is probably great if it suits your needs, ie. if you have nagios (or if you want to use nagios) and you want to be able to make some graphs from your probes performance data, and/or  if you need a good probe for postgresql (for alerting purpose for instance).  The main benefit (and disadvantage) comes from relying on nagios, so it's more about "why is nagios great" or "does it suits your needs".  I'm not sure how we can document this any further.

Powa and PGObserver are different tools with different purpose.  Powa is a focused on performance, with low retention but high precision, and PGObserver is mainly focused on stored procedures performance (but still provides other metrics).

**Comment by guettli** [comment]
Thank you for your reply.
