### ISSUE TITLE
pg_upgrade fails

### ISSUE THREAD

**Issue by Krysztophe** [OPMDG/opm-doc#18]
pg_upgrade of an OPM database fails with the following error message. The `api` table is part of opm-core. Documenting a turnaround would be fine (I didn't try).

```console
Your installation contains one of the reg* data types in user tables.
These data types reference system OIDs that are not preserved by
pg_upgrade, so this cluster cannot currently be upgraded.  You can
remove the problem tables and restart the upgrade.  A list of the problem
columns is in the file:
    tables_using_reg.txt
```
```bash
cat tables_using_reg.txt 
Database: opm
  public.api.proc
  public.api_pkey.proc
```

**Comment by rjuju** [comment]
Ah, I was afraid there was some problem with pg_upgrade.  After some digging, I already opened an issue for that some time ago, but never had the time to work on it: https://github.com/OPMDG/opm-core/issues/47

**Comment by Krysztophe** [comment]
That's it.

**Comment by ioguix** [comment]
This has been fixed. Thanks,
