### ISSUE TITLE
OPM client issue

### ISSUE THREAD

**Issue by cl821615** [OPMDG/opm-doc#7]
Hi Team,

I have installed OPM and but unable to see any clients.Could you please let me know what has to be done in destination server.

**Comment by rjuju** [comment]
Hello,

Can you try this documentation http://opm.readthedocs.org/general/common_problems.html ?

Please report if your issue isn't documented or if something isn't clear enough.

Regards.

**Comment by rjuju** [comment]
Hello,

Do you still have some problems that need to be solved?
